version: '3'

services:
  server:
    image: ghcr.io/maliksayyed/az-backend/prod-server
    container_name: server
    restart: always
    env_file:
      - .env
    ports:
      - "3000:3000"
    networks:
      - aws

networks:
  aws:
    external: true

