name: dev-Server

on:
  push:
    branches:
      - dev
    tags:
      - v*
  pull_request:

env:
  IMAGE_NAME: dev-server

jobs:
  build:
    runs-on: ubuntu-latest
    if: github.event_name == 'push'
    permissions:
      contents: read
      packages: write
    defaults:
      run:
        shell: bash
    steps:
      - name: Checkout repository
        uses: actions/checkout@v2

      - name: Build image
        run: docker build . --file Dockerfile --tag ${{ env.IMAGE_NAME }}

      - name: Log into registry
        run: echo "${{ secrets.TOKEN }}" | docker login ghcr.io -u ${{ github.actor }} --password-stdin

      - name: Push image
        run: |
          IMAGE_ID=ghcr.io/${{ github.repository }}/${{ env.IMAGE_NAME }}
          IMAGE_ID=$(echo $IMAGE_ID | tr '[A-Z]' '[a-z]')
          VERSION=$(echo "${{ github.ref }}" | sed -e 's,.*/\(.*\),\1,')
          [[ "${{ github.ref }}" == "refs/tags/"* ]] && VERSION=$(echo $VERSION | sed -e 's/^v//')
          [ "$VERSION" == "dev" ] && VERSION=latest
          echo IMAGE_ID=$IMAGE_ID
          echo VERSION=$VERSION
          docker tag ${{ env.IMAGE_NAME }} $IMAGE_ID:$VERSION
          docker push $IMAGE_ID:$VERSION

  deploy:
    needs: build
    runs-on: ubuntu-latest
    env:
      GLOBAL_BUNDLE_PATH: /home/ubuntu/global-bundle.pem
    steps:
      - name: Checkout repository
        uses: actions/checkout@v2

      - name: Copy global-bundle.pem
        run: |
          mkdir -p /home/ubuntu
          cp ./config/global-bundle.pem ${{ env.GLOBAL_BUNDLE_PATH }}

      - name: Executing remote SSH commands using SSH key
        uses: appleboy/ssh-action@master
        with:
          host: ${{ secrets.DEV_SERVER_URL }}
          username: ubuntu
          key: ${{ secrets.DEV_SSH_KEY }}
          script: sh deploy-backend.sh

      - name: Run Tests
        env:
          MONGO_URI: mongodb://sayyed:sayyed123@docdb.cluster-cy9ybcici52y.us-east-1.docdb.amazonaws.com:27017/?tls=true&tlsCAFile=${{ env.GLOBAL_BUNDLE_PATH }}&replicaSet=rs0&readPreference=secondaryPreferred&retryWrites=false
        run: npm test
